### PR TITLE
ACS 23 naming?

### PR DESCRIPTION
**Pull request by dgradecak**
- upgrade of testing libraries
- removing jakarta servlet-api incompatible profiles
- version bump to 9.0.0? should we use 23.x to make it easier to follow alfresco versions?

### CODE REVIEW

**Comment by dgradecak** [comment]
@niklassjo do you have any opinion about the versioning? 

I am not quite sure if alfresco-mvc should distinguish the jakarta servlet-api problem and move to 23.x to make it easier to follow?

**Comment by niklassjo** [comment]
> @niklassjo do you have any opinion about the versioning?
> 
> I am not quite sure if alfresco-mvc should distinguish the jakarta servlet-api problem and move to 23.x to make it easier to follow?

I guess it could make sense to follow the alfresco versioning @dgradecak .

**Comment by niklassjo** [comment]
@dgradecak have you decided about the version? should I merge this PR?

**Comment by dgradecak** [comment]
I did not have time to check if all works at runtime with Alfresco 23.x. Did you try to run it?

**Comment by niklassjo** [comment]
> I did not have time to check if all works at runtime with Alfresco 23.x. Did you try to run it?

I have tested MVC parts and it works as far as I can see. Not sure if I have tested all features though.

I have not tested the AOP parts since we don't use them.

**Pull request closed without merging**
